# SPDX-FileCopyrightText: 2025 Danila Gorelko <hello@danilax86.space>
#
# SPDX-License-Identifier: MIT

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: metrics
      POSTGRES_PASSWORD: metrics
      POSTGRES_DB: metrics
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U metrics -d metrics" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      DATABASE_URL: "postgres://metrics:metrics@postgres:5432/metrics?sslmode=disable"
      GITLAB_TOKEN: ${GITLAB_TOKEN}
      GITLAB_HOST_URL: ${GITLAB_HOST_URL}
      GITLAB_PROJECT_NAMES: ${GITLAB_PROJECT_NAMES}
      CACHE_TTL: ${CACHE_TTL}
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: