# SPDX-FileCopyrightText: 2025 Danila Gorelko <hello@danilax86.space>
#
# SPDX-License-Identifier: MIT

name: reuse
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  reuse:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: fsfe/reuse-action@v5